import { ClientModel } from '../model/client.model';
import { CoachModel } from '../model/coach.model';

export const coachList: CoachModel[] = [
  {
    id: 0,
    name: 'Mario',
    surname: 'Rossi',
    age: 35,
    bio: 'Lorem',
    studyTitle: ['Laurea'],
    offeredCourse: ['body building'],
    mail: 'Mario.Rossi @mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 1,
    name: 'Rita',
    surname: 'Verdi',
    age: 35,
    bio: 'da 20 anni insegna con passione e dedizione',
    studyTitle: ['Laurea'],
    offeredCourse: ['body building', 'funzionale'],
    mail: 'Rita.Verdi @mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 2,
    name: 'Marco',
    surname: 'Rossi',
    age: 35,
    bio: 'Lorem',
    studyTitle: ['Laurea'],
    offeredCourse: ['kick boxing', 'funzionale'],
    mail: 'Marco.Rossi @mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 3,
    name: 'Tommaso',
    surname: 'Giallo',
    age: 35,
    bio: 'Lorem',
    studyTitle: ['Laurea'],
    offeredCourse: ['body building'],
    mail: 'Tommaso.Giallo @mail.com',
    psw: '123',
    sex: 'M',
  },
];

export const clientList: ClientModel[] = [
  {
    id: 0,
    name: 'Mario',
    surname: 'Rossi',
    age: 35,
    bio: 'Lorem',
    mail: 'Mario.Rossi@mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 1,
    name: 'Rita',
    surname: 'Verdi',
    age: 35,
    bio: 'da 20 anni insegna con passione e dedizione',
    mail: 'Rita.Verdi@mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 2,
    name: 'Marco',
    surname: 'Rossi',
    age: 35,
    bio: 'Lorem',
    mail: 'Marco.Rossi@mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 3,
    name: 'Tommaso',
    surname: 'Giallo',
    age: 35,
    bio: 'Lorem',
    mail: 'Tommaso.Giallo@mail.com',
    psw: '123',
    sex: 'M',
  },
];
