import { ClientModel } from '../model/client.model';
import { CoachModel } from '../model/coach.model';

export const coachList: CoachModel[] = [
  {
    id: 0,
    name: 'Mario',
    surname: 'Rossi',
    age: 35,
    bio: `Ehilà! Sono un personal trainer con la passione di aiutare le persone a raggiungere i propri obiettivi di fitness. Che tu stia appena iniziando o cercando di intensificare la tua routine attuale, ti ho coperto. Con un focus sul movimento funzionale e un approccio personalizzato per ogni cliente, mi assicurerò che tu veda i risultati e ti goda il processo lungo il percorso. Facciamoci forza insieme!`,
    studyTitle: ['Laurea'],
    offeredCourse: ['body building'],
    mail: 'Mario.Rossi @mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 1,
    name: 'Rita',
    surname: 'Verdi',
    age: 35,
    bio: 'Ehilà! Sono un personal trainer certificato e appassionato di fitness. Aiutare i miei clienti a raggiungere i loro obiettivi di salute e fitness è la mia passione e ciò che mi motiva. Che tu stia cercando di perdere qualche chilo, tonificare o aumentare la forza, sono qui per guidarti e motivarti in ogni fase del percorso. Lavoriamo insieme per raggiungere i tuoi obiettivi di fitness e vivere la tua vita più sana!',
    studyTitle: ['Laurea'],
    offeredCourse: ['body building', 'funzionale'],
    mail: 'Rita.Verdi @mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 2,
    name: 'Marco',
    surname: 'Rossi',
    age: 35,
    bio: `Ehilà! 👋 Sono un personal trainer appassionato che ama aiutare le persone a raggiungere i propri obiettivi di fitness e migliorare il proprio benessere generale. Con anni di esperienza e un focus sull'allenamento funzionale, mi dedico a rendere gli allenamenti divertenti ed efficaci per tutti i miei clienti. Fuori dalla palestra, puoi trovarmi mentre faccio escursioni nella natura o sperimento nuove ricette salutari in cucina. Pronto a unirti a me per diventare la versione più sana di te stesso? Connettiamoci e iniziamo! 💪`,
    studyTitle: ['Laurea'],
    offeredCourse: ['kick boxing', 'funzionale'],
    mail: 'Marco.Rossi @mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 3,
    name: 'Tommaso',
    surname: 'Giallo',
    age: 35,
    bio: 'Ehilà! Sono un personal trainer e adoro aiutare le persone a raggiungere i loro obiettivi di fitness. Che tu stia cercando di aumentare la massa muscolare, perdere peso o semplicemente sentirti più sicuro di te stesso, sono qui per supportarti in ogni fase del percorso. Con la mia esperienza e competenza, sono fiducioso che possiamo creare un piano di fitness personalizzato che funzioni per te e per le tue esigenze specifiche. Sudiamo insieme e facciamo dei seri guadagni! 💪🏋️‍♀️',
    studyTitle: ['Laurea'],
    offeredCourse: ['body building'],
    mail: 'Tommaso.Giallo @mail.com',
    psw: '123',
    sex: 'M',
  },
];

export const clientList: ClientModel[] = [
  {
    id: 0,
    name: 'Mario',
    surname: 'Rossi',
    age: 35,
    bio: `Ciao a tutti! Sono entusiasta di far parte di questa fantastica comunità. Sono un dipendente che ha una passione per l'apprendimento e la crescita nel mio ruolo. Amo portare sul tavolo nuove idee e collaborare con i miei colleghi per raggiungere obiettivi comuni. Quando non lavoro, puoi trovarmi mentre esploro i grandi spazi aperti o mi concedo il mio hobby preferito: leggere. Connettiamoci e conosciamoci!`,
    mail: 'Mario.Rossi@mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 1,
    name: 'Rita',
    surname: 'Verdi',
    age: 35,
    bio: 'Ehilà! Piacere di conoscerti! Sono un dipendente che si occupa di diffondere positività e buone vibrazioni. Adoro creare connessioni con le persone e collaborare a progetti entusiasmanti. Che si tratti di lavorare sodo per raggiungere obiettivi o rilassarmi con amici e familiari, sono sempre pronto per qualsiasi cosa divertente e coinvolgente. Connettiamoci e vediamo dove ci porta la vita!',
    mail: 'Rita.Verdi@mail.com',
    psw: '123',
    sex: 'M',
  },
  {
    id: 2,
    name: 'Marco',
    surname: 'Rossi',
    age: 35,
    bio: `Ciao! Sono felice di essere qui ed entusiasta di connettermi con tutti voi! In poche parole, sono un dipendente che ama lavorare sodo per contribuire al successo della nostra attività. Porto un atteggiamento positivo in tutto ciò che faccio e prospero quando collaboro con gli altri.`,
    mail: 'Marco.Rossi@mail.com',
    psw: '123',
    sex: 'M',
  },
];
